### ISSUE TITLE
Refactor structlog logger creation

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#102]
Currently we are creating the logger in cliquet/__init__.py, before importing thing that need to import the logger as well.

We should move that to another file in order to avoid to have to import it in the middle of the loading list.

See: https://github.com/mozilla-services/cliquet/blob/master/cliquet/__init__.py#L17-L18

**Comment by leplatrem** [comment]
Related #173

**Comment by leplatrem** [comment]
Is that really a problem?

**Comment by Natim** [comment]
Maybe not :)
