### ISSUE TITLE
Add a flag to disable the automatic redirection

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#107]
Currently there is an automatic redirection of all the resources which aren't prefixed by a version number.

The redirection happens in `cliquet.__init__`. To resolve this it's as easy as adding a new flag in the configuration and do not calling the redirection handler in this file.

The flag could be something like ``cliquet.version_prefix_redirect_enabled`` ?

hints:
- use `asbool` to cast the value of the config
- be sure to add tests
- be sure to add documentation
- default behaviour should be to let it on.

**Comment by hiromipaw** [comment]
Hey, if it is ok for you I'd like to pick this up... please let me know...

**Comment by ametaireau** [comment]
Sure, you can go ahead with this Silvia!

**Comment by leplatrem** [comment]
Merged
