### ISSUE TITLE
usjon escape issue

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#131]
As seen in https://github.com/mozilla-services/readinglist/issues/205 we have issues with URLs.

https://github.com/esnme/ultrajson/issues/110

I am going to remove ujson for the time being, but a better long term solution might be to sanity check the escaped / before the queries are done.

**Comment by tarekziade** [comment]
see https://github.com/mozilla-services/cliquet/pull/132

**Comment by pdehaan** [comment]
@tarekziade Did you want to close this now that #132 is merged, or keep it open?

**Comment by leplatrem** [comment]
As a side note here:

PostgreSQL gets rid of the escaping. The problem was on the python side (see PR #142)

```
postgres=# INSERT INTO records(user_id, resource_name, data) VALUES ('','','{"yeah": "\/etc\/hosts"}'::json);
INSERT 0 1
postgres=# SELECT data->>'yeah' FROM records;
  ?column?  
------------
 /etc/hosts
(1 row)

postgres=# 

```
