### ISSUE TITLE
Control settings values coercion

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#133]
Instead of having:

```python
DEFAULT_SETTINGS = {
    'feature_enabled', False
}

....
settings[key] = utils.native_value(settings[key])
```

I propose we do:

```python
DEFAULT_SETTINGS = [
    ('feature_enabled', False, asbool),
    ('feature_ttl', 42, int),
    ('hostname', 'unknown')
]

name, value, coercion = setting[i] + (str,)
settings[name] = coercion(value)
```

**Comment by ametaireau** [comment]
It seems to me we're trying to reinvent things which already exist. I like the idea of enhancing konfig for this kind of things.

**Comment by leplatrem** [comment]
+1 for not for reinventing :)

From what I understood, Konfig reads an INI file.

In included modules of Pyramid, it looks like we don't have access the original INI file path

Should we add *(another)* option to ``initialize_cliquet`` ?

```python
def main(global_config, **settings):
    ini_file = global_config['__file__']
    ...
    initialize_cliquet(..., config_file=ini_file)
```

**Comment by Natim** [comment]
AFAIK this is now handled using the ``DEFAULT_SETTINGS`` parameter.

See: https://github.com/mozilla-services/kinto/blob/master/kinto/__init__.py#L26

@leplatrem Feel free to reopen if the current behavior doesn't fit what you want.
