### ISSUE TITLE
Add schema option to index resource fields

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#134]
This way, we could create indices on records ``data->field``.

This only makes sense in terms of performance for large collections of records **per user**.

**Comment by ametaireau** [comment]
Which is exactly our need for the readinglist and for kinto ;)

**Comment by tarekziade** [comment]
@leplatrem is this still relevant?

**Comment by leplatrem** [comment]
Well, right now, I would say no.
