### ISSUE TITLE
Add a flag for all options cliquet exposes in initialize_cliquet

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#137]
A lot of things are hapenning in the initialize_cliquet, and one would benefit from having these enabled / disabled, so we should pref everything.

**Comment by leplatrem** [comment]
A thought: 

What if, instead of having a lot of settings named ``<feature>_enabled``, we had this : 

```ini
cliquet.initialization_steps =  cliquet.monkey_patch_json
                                cliquet.load_default_settings
                                cliquet.setup_logging
                                cliquet.handle_api_redirection
                                cliquet.setup_end_of_life
                                cliquet.setup_auth
                                cliquet.setup_statsd

```

Each hook would just receive the ``config`` object as parameter.

This way any project could add/replace/remove initialization setup steps :)

**Comment by Natim** [comment]
I think @leplatrem was merged :)

**Comment by leplatrem** [comment]
We didn't resolve exactly resolved this.

As @ametaireau suggested, the current implementation has drawbacks:

> Also, this approach doesn't allow to easily manipulate the steps, like
> we would do in python for instance (add, remove). I'm not sure what we
> should do about that (add more settings with a remove or add prefix?)
> but if we consider explicit is better than implicit then that should work out.
