### ISSUE TITLE
Basic schema migration implementation in PG storage backend

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#139]
I propose that we store a ``schema_version`` (simple integer) in the ``metadata`` table.

Then on startup, instead of checking the existance of the ``records`` like we do currently, we compare the schema versions.

For each missing intermediary version, we run the script ``migration_N_N+1.sql``. Each migration script would update the ``schema_version`` value.

The ``schema.sql`` would always contain the last version of the schema and end up by setting the ``schema_version`` value.

**Comment by ametaireau** [comment]
+1 this seems simple enough.
