### ISSUE TITLE
For HEAD requests, do not fetch from storage

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#140]
Add implicit ``limit=1`` for HEAD requests ?

**Comment by leplatrem** [comment]
With the current implementation, since we use the size of fetch records from storage for the pagination mecanism, adding this change would prevent a client to obtain the ``Next-Page`` via a ``HEAD`` request.

**Comment by Natim** [comment]
>  adding this change would prevent a client to obtain the Next-Page via a HEAD request.

Maybe it is a feature ?

**Comment by tarekziade** [comment]
Is anyone client using the HEAD API ? What's the actual use case ? if the actual use case does not require pagination let's do this
