### ISSUE TITLE
Cliquet logo

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#144]
We draw something using one of those images : 

Bicycle wheel : 

![doubletime_hub_position2_grey](https://cloud.githubusercontent.com/assets/546692/6783612/ed7d16ba-d17a-11e4-86b1-5e356653b737.jpg) from X0 hubs

Simplest mecanism : 

![pawl--ratchet-system](https://cloud.githubusercontent.com/assets/546692/6783615/ed89b884-d17a-11e4-9a59-198e3ac5ea21.jpg)
![ratchet](https://cloud.githubusercontent.com/assets/546692/6783616/ed93cf68-d17a-11e4-8601-1a00634f23fa.png)
![gsed_0001_0028_0_img8951](https://cloud.githubusercontent.com/assets/546692/6783656/4a0abbee-d17b-11e4-80c1-e785022d378a.png)

The tool itself : 
![i_559292](https://cloud.githubusercontent.com/assets/546692/6783757/da907b18-d17b-11e4-9fae-3f4f754c05f0.jpg)

The toolbox (from above for example) : 
![coffret-nano-38-outils-cliquet-1-4-etanche-facom-rl-nano1pb-123-1](https://cloud.githubusercontent.com/assets/546692/6783759/de152482-d17b-11e4-881b-f52cece09846.jpg)

![0965-014-32-tif](https://cloud.githubusercontent.com/assets/546692/6783776/f4c921f6-d17b-11e4-9a0b-bfe635c96be9.jpg)

**Comment by ametaireau** [comment]
I love the "ratchet" schemas.

![ratchet](https://cloud.githubusercontent.com/assets/546692/6783616/ed93cf68-d17a-11e4-8601-1a00634f23fa.png)
![gsed_0001_0028_0_img8951](https://cloud.githubusercontent.com/assets/546692/6783656/4a0abbee-d17b-11e4-80c1-e785022d378a.png)

**Comment by tarekziade** [comment]
+1 for 

![ratchet](https://cloud.githubusercontent.com/assets/546692/6783616/ed93cf68-d17a-11e4-8601-1a00634f23fa.png)

**Comment by Natim** [comment]
Yep I like it too.

**Comment by leplatrem** [comment]
![g3046](https://cloud.githubusercontent.com/assets/546692/7125354/7b7f7ece-e230-11e4-848b-760b0e645f13.png)
![rect3052](https://cloud.githubusercontent.com/assets/546692/7125355/7b82ba80-e230-11e4-8e99-b8ff6c8abf18.png)
![rect3052-5](https://cloud.githubusercontent.com/assets/546692/7125356/7b89794c-e230-11e4-910c-c368cee38e43.png)
![rect3052-6](https://cloud.githubusercontent.com/assets/546692/7125357/7b8dd8ca-e230-11e4-9616-ee045952412b.png)
![rect3052-7](https://cloud.githubusercontent.com/assets/546692/7125358/7b93a110-e230-11e4-89db-ced66fed6708.png)
![rect3052-8](https://cloud.githubusercontent.com/assets/546692/7125359/7b986f10-e230-11e4-85d4-ab604fbb4c63.png)
![rect3052-9](https://cloud.githubusercontent.com/assets/546692/7125360/7b994782-e230-11e4-9608-1ab4e0b30544.png)
![rect3052-10](https://cloud.githubusercontent.com/assets/546692/7125361/7b9e6eba-e230-11e4-965e-d04c397daeb7.png)
![rect3052-11](https://cloud.githubusercontent.com/assets/546692/7125362/7ba4d502-e230-11e4-8dd1-01295be065f5.png)

Feedback ? :)

**Comment by Natim** [comment]
I prefer the one with the hole inside and the green one is my favorite of them

**Comment by Natim** [comment]
**Cliquet: Move web services forward.**

**Comment by ametaireau** [comment]
The green seems too green for me. I like the last one, or maybe the green with a less flashy color?

**Comment by leplatrem** [comment]
Some more then :)

![rect3052-12](https://cloud.githubusercontent.com/assets/546692/7133149/9ab21922-e290-11e4-93c0-b3a0cc1e14e1.png)
![rect3052-13](https://cloud.githubusercontent.com/assets/546692/7133167/e3db94a2-e290-11e4-9f85-71e91d7fd118.png)
![rect3052-16](https://cloud.githubusercontent.com/assets/546692/7133168/e3dcf3ba-e290-11e4-82c5-86a011e9df9a.png)
![rect3052-17](https://cloud.githubusercontent.com/assets/546692/7133169/e3dfa704-e290-11e4-917e-5a1131c906f6.png)
![rect3052-18](https://cloud.githubusercontent.com/assets/546692/7133170/e3e0ad98-e290-11e4-95d7-d43502f64461.png)

**Comment by Natim** [comment]
I prefer the ratchet on the right hand side

**Comment by n1k0** [comment]
Will it come in pink? Just asking.

**Comment by leplatrem** [comment]
![rect3052-21](https://cloud.githubusercontent.com/assets/546692/7133893/18c0b92a-e298-11e4-9eed-510f43e9adb9.png)
![rect3052-22](https://cloud.githubusercontent.com/assets/546692/7133892/18bf85f0-e298-11e4-9204-dfcbb18c45e4.png)

**Comment by Natim** [comment]
I like the last one in violet/pink :)

**Comment by ametaireau** [comment]
Should we try to add an arrow or something? I was actually more thinking about a blueprint of some sort as a logo.

**Comment by leplatrem** [comment]
![rect3052-24](https://cloud.githubusercontent.com/assets/546692/7134481/84df35d2-e29d-11e4-9a04-79fc508ac03a.png)

**Comment by ametaireau** [comment]
Yep, I feel more the spirit of it.
