### ISSUE TITLE
Automatic Server-side Conflict Resolution like Dropbox's Datastore

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#153]
This blog post describes what Dropbox did for resolving conflicts.

https://blogs.dropbox.com/developers/2013/07/how-the-datastore-api-handles-conflicts-part-1-basics-of-offline-conflict-handling/

tldr: the client tells the server how to resolve the conflicts if any,

See the setResolutionRule() API in https://www.dropbox.com/developers/datastore/docs

I think we want something similar in Cliquet.

**Comment by Natim** [comment]
This is already possible with the current API we should add a paragraph in the documentation for it.

**Comment by Natim** [comment]
Note that it is possible for "server wins" and "client wins" strategy but not for 3-ways merge.

Also has we don't have the previous version of the record on server side, I am not sure that we can implement the three-leg merge on server side.

**Comment by Natim** [comment]
This has been implemented in Kinto.js http://kintojs.readthedocs.org/en/latest/api/#fetching-and-publishing-changes

Basically that's it: https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L702-L713

**Comment by leplatrem** [comment]
We can't implement 3 ways merge on the server since we don't keep the old versions.

Closing :)
