### ISSUE TITLE
Use redislite for in-memory backend

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#160]
We should use [redislite](https://pypi.python.org/pypi/redislite) as a backend, see https://github.com/mozilla-services/cliquet/pull/127

**Comment by Natim** [comment]
I am not a big fan even if I understand the benefit.

**Comment by ametaireau** [comment]
Do you mean you would prefer to use another backend (in memory ?)

**Comment by Natim** [comment]
I guess yes.

**Comment by ametaireau** [comment]
The good thing with this is that we can get an in-memory backend without having to write / maintain extra code :)
