### ISSUE TITLE
Add a "readinglist" prefix for statsd metrics

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#161]
Currently, we send information to statsd using `storage.{something}` or `cache.{something}`, and as such we're missing the `readinglist` prefix.

**Comment by Natim** [comment]
We should prefix with the env as well (prod, stage)

**Comment by Natim** [comment]
Simplepush uses ``simplepush.prod.module.submodule.key``

**Comment by leplatrem** [comment]
We should prefix with the project_name then
