### ISSUE TITLE
Structlog logging is costly

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#173]
Notes:

* Reference pstats graph http://img.933k.org/images/profilcxc.png
* Without structlog in the batch view http://img.933k.org/images/profilgog.png
* Without structlog at all http://img.933k.org/images/profilusu.png

In our implementation, every information bound on the logger is shared by thread.

This allows us to bind in some place and dump out in some other place:
* https://github.com/mozilla-services/cliquet/blob/master/cliquet/resource.py#L67
* https://github.com/mozilla-services/cliquet/blob/master/cliquet/logs.py#L69

Should this be changed for a logger local the request instead ?
``request.registry.logger = logger.bind(user_id=...)``

Also, the subrequests logging could be implemented differently. With the current implementation, subrequests logging overwrites the bound info of the main request logger (the one coming from POST /batch).

See https://github.com/mozilla-services/cliquet/blob/master/cliquet/views/batch.py#L118-L123

It looks like this could be improved :)

**Comment by hynek** [comment]
Would something like a concept of a process-global context help such that the (thread local) contexts carry only the locally relevant data and those contexts get combined on logging out?

**Comment by leplatrem** [comment]
@hynek thanks for your proposal! That looks like a good potential solution indeed.

But as you can see this issue is somewhat old. We haven't spent too much efforts on it recently.

Our use-case is to log the current request details when the response kicks out.

Alternatively, instead of using the logger *bound local context* to accumulate details along the request processing, we could also store those on a request attribute, and use `logger.info()` with the resulting data when the response is served.

Something like:

```python
def some_view(request):
     # ...
     request.bound_data['collection_id'] = 'some value'
     # ...
     return {...}


def on_new_response(event):
      request_details = event.request.bound_data
      logger.info(**request_details)

config.add_event_listener(on_new_response, NewResponse)
```

I think that would do it too. If you have some other usecases where thread local contexts are relevant, and you are wiling to implement it, that's awesome! it would be a cleaner than this!

Thanks for reaching out here!

**Comment by tarekziade** [comment]
moved to https://github.com/Kinto/kinto/issues/603
