### ISSUE TITLE
Pypy support

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#207]
* Add a toggle to use a pypy compatible psycopg lib (pyscopg2ccfi, psycopg2ct...)
* Add a TravisCI Pypy target

**Comment by brouberol** [comment]
Regarding the toggle, are you thinking about something like ``pip install cliquet[postgresql+pypy]``, that would install the required psycopg lib?

**Comment by Natim** [comment]
It could also be just in the documentation and the toogle might takes places in the tox.ini file.
