### ISSUE TITLE
Add key prefix option for cache

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#227]
* Add a setting ``cliquet.cache_prefix`` (default: ``''``)
* Every cache entry key is prefixed by ``self.prefix`` in cache backend classes

**Comment by lavish205** [comment]
I want to work on this bug, looking forward for instructions to start.

**Comment by leplatrem** [comment]
When a key is passed to a method of the cache backend (e.g. [here](https://github.com/mozilla-services/cliquet/blob/master/cliquet/cache/memory.py#L27)), it should be concatenated to a `prefix` coming from the settings.

That means the key prefix should be passed to the constructor of cache backend (e.g. [here](https://github.com/mozilla-services/cliquet/blob/master/cliquet/cache/memory.py#L53-L54))

**Comment by lavish205** [comment]
I have few doubts
- In which file we are supposed to add a setting `cliquet.cache_prefix` (default: `''`)
- What is `self.prefix` exactly here? I can't see any variable named `prefix` in CacheBase class.
- And if it is supposed to passed to constructor [here](https://github.com/mozilla-services/cliquet/blob/master/cliquet/cache/memory.py#L53-L54), then what will be the value of key prefix?

**Comment by leplatrem** [comment]
I will try to answer your questions:

> In which file we are supposed to add a setting

in `cliquet/__init__.py`, you define the default settings values.

> What is `self.prefix` exactly here?

This is value received from the constructor of the Cache backend. It does not exist yet and should be added.
It will be used in the cache backend to concatenate with the key passed in arguments of each method.

>  what will be the value of key prefix ?

in the `load_from_config` function, you obtain the setting from the `config` object:

```python
settings = config.get_settings()
prefix = settings['cache_prefix']
backend = Cache(prefix=prefix)
return backend
```

Hope this helps ;)
