### ISSUE TITLE
OAuth scopes in pyramid principals

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#239]
Currently the scopes obtain from OAuth token are not exposed outside the authentication class. 

I propose that we add them to ``effective_principals`` to allow the implementation of an authorization policy that would rely on those scopes.

**Comment by leplatrem** [comment]
This is now out of scope. It should be done in cliquet-fxa or other authentication policies.

**Comment by Natim** [comment]
I do not 100% agree with you here, because we still need to fix the permission issues when we want to reduce the token permissions for a user to a given to a bucket/collection scope or a read/write/create scope.

**Comment by Natim** [comment]
Oh sorry for the misunderstanding. This issues was not about managing permissions from scopes but managing principals from scopes. So you were right to close it.
