### ISSUE TITLE
Allow usage of any schema validation library

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#244]
It looks that some of Cliquet code is tight to Colander.

For example https://github.com/mozilla-services/cliquet/blob/master/cliquet/resource.py#L102-L106

I wonder what would it take to open validation to any lib like wtf, Cerberus, json_schema, ...

**Comment by ametaireau** [comment]
I think it's a matter of definig all the interactions we need with the validation library and have a wrapper which does the encapsuling for us.

For instance, here, the Resource class just needs a `get_unvalidated_data` method of some sort and we are good!

**Comment by tarekziade** [comment]
what's the use case to make this pluggable ? Looks like colander is good enough for what we need in Kinto -- why someone would want to move it to another validator ?

**Comment by tarekziade** [comment]
Please reopen on Kinto side if that's still relevant
