### ISSUE TITLE
Timestamp uniqueness by parent_id under heavy load

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#25]
A DB constraint was added to guarantee uniqueness of timestamps, per user, per collection.

The current version of the ``bump_timestamp()`` SQL function does not resist to *(very very high)* load by **one user**. In other words, when more than **two requests of the same user** are handled in **less than 2 msecs**.

For example, running several instances of this script in parallel will raise integrity errors (*~4/10000 when running 3 instances on my devbox*):

```python
import psycopg2
import psycopg2.extensions

conn = psycopg2.connect(dbname='testdb', host='localhost', user='postgres', password='postgres')
cursor = conn.cursor()

nberrors = 0

for i in range(10000):
    try:
        cursor.execute("INSERT INTO records(user_id, resource_name, data) VALUES ('', '', '{}')")
        conn.commit()
        if i % 100:
            print '.',
    except psycopg2.Error as e:
        nberrors += 1
        conn.rollback()
        print e

print nberrors, 'errors'
````

**Comment by tarekziade** [comment]
> when more than two requests of the same user are handled in less than 2 msecs

Can this really happen in the real world ? Also, since we are using transaction now, are we still triggering that function for every row ? or could we have the event triggered at the transaction level

**Comment by leplatrem** [comment]
I posted a simplified version of this on http://stackoverflow.com/questions/34817760/how-to-generate-unique-timestamps-in-postgresql

We could do as it is done for Sync:

* add another column with a sequence
* use the sequence as fake decimals `"%s.%s" % (last_modified, sequence)` for timestamps

**Comment by tarekziade** [comment]
moved to https://github.com/Kinto/kinto/issues/602
