### ISSUE TITLE
Is there a way to store binary media files on cliquet?

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/cliquet#253]
For instance, on CouchDB, you can add binary attachments to documents. It looks like on cliquet this is not possible? I'm thinking of things like photos, mp3 files, maybe some videos.

**Comment by Natim** [comment]
This is on the roadmap. What we did for daybed was to create a BLOB type in the schema to let you do that without indexing binary data in Elasticsearch for instance.

The plan for cliquet is to work on a document oriented api to let you handle that. It will become a priority as soon as we have a specific usecase for it but it is definitely something we want.

**Comment by michielbdejong** [comment]
Cool! I really like cliquet :)

**Comment by leplatrem** [comment]
Thanks :) We started to write about this in #236 

Right now, we will focus on our internal goals, and binary files are not a priority. Once we have this feature, we want to make Kinto (our generic storage built with Cliquet) compatible with the *Remote Storage* spec, as you may have read in the article :)
