### ISSUE TITLE
Replace Cliquet protocol by JSON-Api spec ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#254]
Yesterday I assisted to @steveklabnik talk about the [JSON-API spec](http://jsonapi.org/about/) at [APIdays BCN](http://mediterranea.apidays.io/).

I was amazed by the number of intentions we have in common! And, although we completely ignored its existence, [the protocol we designed for Cliquet](http://cliquet.readthedocs.org/en/latest/api/index.html) almost matches their spec! That's icing on the cake :)

Shared goals:

* save the developers the hassle of making choices when building a JSON-API;
* convention over configuration;
* simple thus loosely coupled; (*not like a couchdb protocol*)
* easy to debug;
* pagination/sort/filter;
* simple JavaScript clients (Ember data will support it natively in the next version);

Protocol differences:

* so far Cliquet doesn't manage relations between models, so we'll just ignore their work on that for a start;
* the Bulk API is different, and does not look like ours;
* we have a simple concurrency-control model, and that could become an extension (like Bulk);
* we have *conflict* responses regarding records field unicity;
* the use of a dedicated mimetype is kind of overkill, but we could also serve payloads as application/json;
* the pagination querystring param format differs a bit;
* the sort querystring param has ``+`` for ascending order;

I strongly believe that we should put some efforts in adjusting our custom protocol to conform with the JSON-API spec.

Thoughts ?

**Comment by ametaireau** [comment]
Some notes while reading the document:

- I don't understand fully how this specification is different from some other ones (which tend to have a more sementic approach)
- Pagination seems handled with links, where we were using headers, and indicates when it's the "last" page (which we purposely don't do)
- It seems that the records are not returned "as is", but rather in an "attributes" object. Why not but it seems it also could add parsing overhead on the client side?
- I haven't found information about their batch endpoint.

That being said, I think it would be good to have a formalism on the APIs we're exposing, and if this is already being discussed elsewhere, then we definitely should consider it rather than doing or own.

**Comment by leplatrem** [comment]
> I don't understand fully how this specification is different from some other ones (which tend to have a
> more sementic approach)

That was my question to @steveklabnik after the talk. He explained that most hypermedia initiatives tend to focus on semantics. ``JSON-LD`` tends to be like Semantic Web, ``collection+json`` tends to very good for search results, etc..

> I haven't found information about their batch endpoint.

http://jsonapi.org/extensions/bulk/

**Comment by hiromipaw** [comment]
I see you have already opened a discussion about this. 
My reference on https://github.com/mozilla-services/cliquet/pull/247 was only regarding an example of well known patterns.
I simply think each hypermedia type has their own standards and with time more standards will simply arise. So sometimes it is about picking a standard to use that looks appropriate for a certain project.

**Comment by steveklabnik** [comment]
Hey all! Been reading this thread, would be happy to answer any continued questions. Here's some answers to the first ones:

>    I don't understand fully how this specification is different from some other ones (which tend to have a more sementic approach)

As @leplatrem mentions, each type sort of picks some use case they want to be good at. For example, HAL is an experiment in minimalism. Collection+JSON is trying to be the spiritual successor to ATOM. JSON-LD is taking the semantic web approach.

JSON API's tagline here is 'transferring objects over the network boundary,' like is common in many SPAs. I have a blog, it has Posts and Comments and Authors, I want to CRUD with them over the network from some sort of client. While we consider the SPA case specifically, this is something many non-JS applications do too.

>  Pagination seems handled with links, where we were using headers, and indicates when it's the "last" page (which we purposely don't do)

Yeah, we went back and forth, but ended up with them in the body. You can leave off `last` if you want to, or at least, you should be able to, I didn't double-check before writing that :smile: 

>    It seems that the records are not returned "as is", but rather in an "attributes" object. Why not but it seems it also could add parsing overhead on the client side?

Imagine you have a blog post (sorry, my Rails background makes this my go-to example all the time), and, to save network traffic, you want to request both the post and its comments in one request. You have to split out which things are posts and which things are comments. By keeping the same structure in the single case, you pay a tiny overhead in stuff to parse, but drastically simplify the logic of parsing.

>    I haven't found information about their batch endpoint.

It's an extension: http://jsonapi.org/extensions/bulk/

**Comment by Natim** [comment]
> you want to request both the post and its comments [...] You have to split out which things are posts and which things are comments

Well in my understanding not really because in that case comments are an attribute of the post.

    {
      "id": "post_id",
      "title": "My blog post",
      "comments": [
        {"id": "comment-1", "text": "Here is my comment", "author": "natim"},
        {"id": "comment-1", "text": "Here is my second comment", "author": "natim"}
      ]
    }

**Comment by steveklabnik** [comment]
You could do it that way, but that's not the standard way. See the example on the homepage.

Embedding like this comes at a cost: while in your example, the author just has a name, but if there's more information, it gets repeated over and over. By pulling them out, it gets de-duplicated.

**Comment by hiromipaw** [comment]
I +1 what Steve said :). Also in a RESTful world Comments would be another resource that you do not necessarily want to consider as Post attributes.
Otherwise in comments you might think to also include the authors, and even their relationships, like friends or followers, and so on down the chain...
