### ISSUE TITLE
Generate Swagger API declaration

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#257]
Using every declared end-point and protocol, we can generate a skeletton (if not whole) of Swagger file.

For example, using the command-line : ``cliquet --ini server.ini swagger specs.json`` 

During APIdays I realized that Swagger realized became the de-facto standard to describe API endpoints and protocols.

It also for example to generate interactive documentations, API test suites, SDK, API changelogs, ...

https://github.com/swagger-api/swagger-spec

**Comment by ametaireau** [comment]
Swagger is nice, that's true. I started working on integrating swagger in cornice, and there is currently [a pull request with some code written by someone else](https://github.com/mozilla-services/cornice/pull/285).

The PR there should be improved but I like the idea of having the swagger spec available at a specific endpoint, like we did for SPORE.

**Comment by rodo** [comment]
I like it too for sure.

**Comment by tarekziade** [comment]
Is that something we want to do in Kinto or in Cornice ?  Looks like it should be a cornice feature. Closing - feel free to reopen in the Kinto tracker if we want to work on this in Kinto
