### ISSUE TITLE
Split tests from cliquet package

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#267]
I propose that we change the folders layout in the cliquet repository : 

* ``cliquet/tests/support.py`` →  ``cliquet/testing.py``
* ``cliquet/tests/`` → ``tests/``  (*outside cliquet package, along docs*)

Examples of such organization: https://github.com/hynek/structlog/

**Comment by Natim** [comment]
As long as you add the tests directory to the MANIFEST.in

**Comment by Natim** [comment]
The more I think about it the more I think tests are part of the code and I like the fact that we can import some of helpers that we used in cliquet to help writting tests for a cliquet project.

**Comment by leplatrem** [comment]
That would help to split was is part of testing tools from the tests code itself.

Currently we pay no attention to breaking changes we introduce in the tests code. And that can break external projects that import stuff from there (like it happened in Kinto).

**Comment by Natim** [comment]
Ok I see what you mean, also I am not sure the testing API is stable enough yet.

**Comment by ametaireau** [comment]
I share the vision @leplatrem has about this: we should stabilize our tests tools, and make them reliable for other projects.

That being said, I think tests should stay in `cliquet.tests`, since it helps a bunch of people to run them without extra setup (think packagers for instance). Otherwise, a setup.py install doesn't copy the tests and it's not possible to check an installed version worked like it should.

**Comment by Natim** [comment]
Read here https://github.com/benoitbryon/psykorebase/issues/21#issuecomment-126615305

> As a user I don't need to run test on a installed package because continuous integration does it for me. What I may need is a healthcheck to make sure everything is installed correctly.

**Comment by ametaireau** [comment]
The "as a user" part isn't reflecting the whole list of people that want to run the tests.

I was more thinking about OS packaging and automatic build tools (archlinux for instance can have a dependency on the tests when installing IIRC)

**Comment by Natim** [comment]
I think they also need healthcheck
