### ISSUE TITLE
Create a scaffold rule for cliquet applications

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#272]
We could make a cliquet template for pcreate, [as we did for cornice](https://github.com/mozilla-services/cornice/tree/master/cornice/scaffolds) which doesn't require to copy/paste any code.

- [ ] Create the scaffold;
- [ ] Update the documentation;

**Comment by Natim** [comment]
We should have the following architecture:

```
.
├── CHANGELOG.rst
├── config
│   └── <project_name>.ini
├── Makefile
├── README.rst
├── setup.py
├── <project_name>
│   ├── __init__.py
```

**Comment by tarekziade** [comment]
I am going to close this, assuming that building apps on the top of cliquet is not going to happen anymore.

**Comment by Natim** [comment]
> that building apps on the top of cliquet is not going to happen anymore.

However it probably will on top of ``kinto.core``
