### ISSUE TITLE
Add PATCH on collections

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#274]
```
PATCH /articles
{
    "items": [
        {"id": "56t7y8u9", "archived": true},
        {"id": "86r735ty", "title": "Yeah"}
    ]
}
```

Returns the list of modified records.

* ``400`` if ``id`` is missing in some provided record
* ``412`` if with preconditions headers etc.

**Comment by Natim** [comment]
Isn't this already handled by the batch endpoint?

**Comment by leplatrem** [comment]
> Isn't this already handled by the batch endpoint?

Yes, indeed, but this would be resource oriented, and more performant
