### ISSUE TITLE
Uniformize the naming of getters in our classes

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#290]
I've seen that the different contributors to the project don't have the same way to define *getters* on classes.

For instance, on `resource.ViewSet`, I've seen that there are getters prefixed by `get_`, whereas in the *permissions* backend, it's not the case (we have methods named `object_permission_principals` for instance).

In the case of the ViewSet, the design is such that the class can have class attributes (which aren't prefixed by get, because they're attributes) and then getters which start by `get`.

I would advocate we try to follow this pattern everywhere, or update how we do it for viewsets. Thoughts?

**Comment by Natim** [comment]
For the permission backend now that we changed ``object_permission`` with ``ace`` I think it makes sense to add the ``get_``. At first they were there but the method name was too long so I had to remove them. But with ``ace`` it should work.

Also @ametaireau tells me that it may not be the only place where they are missing.

I like the fact that ``get_`` indicate that it is a call and that without the ``get_`` it is a property.
