### ISSUE TITLE
Pluggable id generators

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#292]
Like Koremutake of Daybed https://github.com/spiral-project/daybed/blob/cb5efbf9b2ef326154a638c242d64ae001600ba4/daybed/backends/id_generators.py#L18-L41

**Comment by Natim** [comment]
They are somehow pluggable already, see https://github.com/Kinto/kinto/blob/master/kinto/views/__init__.py#L8-L15

https://github.com/Kinto/kinto/blob/master/kinto/views/buckets.py#L21-L26

But we could let them be pluggable from the configuration as well as we do for storage, cache, listeners and permssions backends.

**Comment by leplatrem** [comment]
Closing since this is already the case :)
