### ISSUE TITLE
Reload config when receiving SIGHUP

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#317]

**Comment by Natim** [comment]
``killall -HUP uwsgi`` works

**Comment by ametaireau** [comment]
Have a look [at the uwsgi documentation](https://uwsgi-docs.readthedocs.org/en/latest/Management.html#reloading-the-server) for more information about what this does.

**Comment by leplatrem** [comment]
I would suggest to add a note in Kinto *'running in production'* documentation though.
