### ISSUE TITLE
Expose batch endpoint configuration in the API.

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#318]
Clients need to know what's the maximum batch operations they can do, in order to split their calls accordingly.

We should expose that in either an extra endpoint or the root one. I would advocate to create another endpoint exposing some public configuration values.

**Comment by leplatrem** [comment]
What about a header that we would get using ``HEAD /batch`` ?

**Comment by ametaireau** [comment]
or just a GET on /batch? I feel using headers for this is a bit counter intuituve.

**Comment by elemoine** [comment]
Or [OPTIONS](http://zacstewart.com/2012/04/14/http-options-method.html) maybe? ;-)

Actually,

```
OPTIONS /batch
{
    "max_requests": 25
}
```

would look good to me.

Another option:

```
GET /batch_max_requests
25
```

My 2 cents.

**Comment by n1k0** [comment]
Ah, that's interesting. In Cliquetis, we're discussing discarding the approach in the patch for https://github.com/mozilla-services/cliquetis/pull/39 with @natim, where a first request is made upon `/` to retrieve the version of the API protocol (from the `url` property of the json body response).

Your suggestion makes me think we could benefit from this single initial request on `/` to fetch other configuration flags as well, like the one we're after here.

That would be a single request for fetching whatever is server settings clients need, while exposing dedicated endpoints to fetch each configuration flag sounds a little crazy from a performance perspective.

**Comment by elemoine** [comment]
Yep, that sounds good to me. And it's consistent with the information `GET /` currently returns.

**Comment by Natim** [comment]
Yes it makes sense.

Also not that there is plan to move ``GET /`` to ``GET /__info__``

**Comment by leplatrem** [comment]
So if I understand correctly, we shall add some attributes in ``GET /`` (a.k.a. hello view):

```
{
    "hello": "kinto",
    "version": "0.1.1",
    ...
    "settings": {
        "cliquet.max_batch_request": 25,
    }
}
```

**Comment by Natim** [comment]
:+1:

**Comment by n1k0** [comment]
Sold.

**Comment by ametaireau** [comment]
I would rather just see "max_batch_endpoint", dropping the "cliquet" prefix.

**Comment by leplatrem** [comment]
> I would rather just see "max_batch_endpoint", dropping the "cliquet" prefix.

I put the prefix deliberately...

Pros:
- its name consistent with the setting name in ``.ini``
- it provides a namespace to some custom settings from application extending cliquet (e.g. ``kinto.flush_enabled``...)

Cons:
- it exposes internal notions (i.e. cliquet) to the client.
- unless cliquet is the name of the protocol, it imposes the word cliquet to other implementations of the server 
- (it is seemly long)

**Comment by Natim** [comment]
```python
import this

The Zen of Python, by Tim Peters
[...]
Namespaces are one honking great idea -- let's do more of those!
```

**Comment by elemoine** [comment]
I'd be +1 on using the "cliquet" namespace, because that makes the setting's origin clear and explicit. I read the response and immediately understand what this setting corresponds to, and where it comes from.

**Comment by ametaireau** [comment]
Goal was to avoid exposing internals to clients, but since it's part of the cliquet protocol, it seems to make sense to expose it.
