### ISSUE TITLE
Add custom Pyramid events

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#32]
* At endpoint level
* At storage level
* At authentication level

**Comment by ametaireau** [comment]
If I understand this correctly, the aim here is to be able to trigger some code when specific events arise.

Let's try to list them.

### At storage level:

- a new resource is created (send resource id)
- a resource had been deleted (resource id)
- a new record had been added (resource id + record id)
- a record had been modified (resource id + record id)
- a record had been deleted (resource id + record id)

### At authentication level:

- A user had failed to authenticate (user id)
- A user has successfully logged in (user id)
- Access had been denied to a resource (resource id + verb + user id)
- Access had been granted to a resource (resource id + verb + user id)

I don't understand what "endpoint level" is, and as such I fail to see which events should be triggered there.

**Comment by Natim** [comment]
For me some of your storage level event are in fact endpoint level events.

You could have event on batch and for most of the event, I think the full record should be present (not only its id).

**Comment by ametaireau** [comment]
I've updated my previous comment to send records rather than record ids.

**Comment by leplatrem** [comment]
> the full record should be present
+1

Indeed, I didn't explicit what would be an "endpoint" :) I meant like incoming request, but Pyramid provides something similar...

Instead, @ametaireau suggested `pre_` and `post_` on storage, which makes more sense

**Comment by Natim** [comment]
How do you handle ``pre_`` and ``past_batch``?

**Comment by Natim** [comment]
The problem I see with event on storage is that you cannot have separate hooks for separate collections.

**Comment by ametaireau** [comment]
It really depends how you implement the event subscriber.

For instance, Let's say you subscribe to all "pre update" events, for all collections.

Then, when your function is triggered, you're given the resource id + the record and you can do routing from there. Your application logic can do anything it feels good to trigger a different hook depending on a routing logic it defines (be it the collection id or anything else).

**Comment by leplatrem** [comment]
Implemented in #488
