### ISSUE TITLE
Add a ProtectedViewSet class

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/cliquet#322]
Currently, the default `ViewSet` class has some behaviour tied to the `ProtectedResource` class. We shouldn't have anything related to protected resources in the default viewset since it's a concept which isn't known to the viewset.

Instead, we should define a new `ProtectedViewSet` which handles this and modify the  `register_resource` method to accept a `protected` argument.

Also, I belive this will be the right timing to split viewsets out of the `resource.py` file.

**Comment by leplatrem** [comment]
+1
