### ISSUE TITLE
Expose cliquet serve command

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#327]
When installing kinto with ``pip install kinto``, I'd like to be able to run:

    cliquet --ini config/kinto.ini serve

For now I've got to do:

    pserve config/kinto.ini

**Comment by ametaireau** [comment]
It's been discussed that this would be a good opportunity to make all the commands use the same name "cliquet" for starting the server, stopping it or running the migrations.

**Comment by ametaireau** [comment]
Also, I wonder if this doesn't belong to kinto directly, I was expecting to have a "kinto" command, which would help me do the following installation steps:

- `pip install kinto` to install;
- `kinto init` would generate the default configuration file;
- `kinto migrate` to run the migrations;
- `kinto start` to start the server.

**Comment by Natim** [comment]
The cliquet command implements already:

  - init
  - migrate

This ticket is to add the missing (serve) command.

We could also add a ``cliquet run_uwsgi``

**Comment by Natim** [comment]
See https://github.com/mozilla-services/cliquet/blob/master/cliquet/scripts/cliquet.py

**Comment by ametaireau** [comment]
That's not what the init command is doing. Also, this is in the scope of kinto so I'll open an issue there.

**Comment by Natim** [comment]
This is a good question. Do we need a ``kinto`` command or can we use a ``cliquet`` command for all the projects using the cliquet toolkit?

**Comment by ametaireau** [comment]
I would like to not expose cliquet to the users who want to install kinto. They don't need to know about it: it should be as easy as `pip install kinto && kinto init && kinto start`.

**Comment by Natim** [comment]
Maybe we can add helper so that it is easy to proxy global cliquet command in the per project (ie kinto) command.

**Comment by n1k0** [comment]
+1 for having a `kinto` command to enforce federation around the name.

**Comment by Natim** [comment]
This has been implemented here:  https://github.com/Kinto/kinto/pull/247
