### ISSUE TITLE
Implement a contribute.json endpoint

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#334]

**Comment by Natim** [comment]
This has been described in a document.

Basically we need to implement a ``__version__`` endpoint with the following:

## Overview

This is a proposal for creating a standard route and format for exposing the version information of an service.  The reason for doing this is to facilitate tooling and make it easy to identify which version of a service that is running.  This spec represents the required fields for any application.  Additional fields can be added as needed.

## Route

``/__version__``

## Required Objects
```
{
    “source”: “URL for the source repository”,
    “version”: “human readable version string”,
    “commit”: “commit hash”
}
```
## Optional Objects

Any additional fields as required by the application in JSON format.

## Definition

``source``
    Source repository for the code base.

    Required: yes
    Type: String

``version``
    The human readable version of the code base that has been deployed

    Required: yes
    Type: String

``commit``
    The commit hash pointing to deployed code in source control

    Required: yes
    Type: String

**Comment by Natim** [comment]
The hard part is the commit on production because we don't deploy with git.
Also we may consider using https://www.mozilla.org/contribute.json

**Comment by ametaireau** [comment]
There is something I don't understand in this proposal. The title talks about a `__info__` endpoint whereas the proposal talks about a `__version__` endpoint.

I'm not clear anymore which problem we're trying to solve, and for who.

From what I understand, adding an `__info__` endpoint would replace the hello view. If so, then we also need to put back the information we have on the hello view in the `__info__` endpoint:

- url
- documentation
- version
- settings
- service name (was named "hello")

Contribute.json seems to have a different scope that what we're trying to do and I would consider adding it nevertheless, but not as a replacement to this `__info__` endpoint.

Also, the commit hash shouldn't be mandatory, as it might show easily that a server is out of date with the latest security fixes, for instance, so I would only activate it for dev environments.

**Comment by Natim** [comment]
> From what I understand, adding an __info__ endpoint would replace the hello view.

Please don't do that. The / endpoint serve other purposes (landing page for people coming through)

**Comment by ametaireau** [comment]
OK. I updated the title of the issue then :)

**Comment by phrawzty** [comment]
From what I understand the actual problem that we're trying to solve is this: Mozilla QA wants a standardised endpoint across all Cloud Serivces apps that exposes certain key information. Perhaps we should back it up a second and talk about the root problem.

Questions:
* Is `/__info__` the endpoint label they want? If not, what is?
* If so, what *exactly* is the information that QA wants to see at that endpoint? Is it the items in [Required Objects](https://github.com/mozilla-services/cliquet/issues/334#issuecomment-125873225) above?
* Can (should?) we expose additional information at this endpoint beyond that required by QA?
