### ISSUE TITLE
Release the permission code as a separate library

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla-services/cliquet#336]
Following this article: http://www.servicedenuages.fr/la-gestion-des-permissions.html the designed permission system seems very interesting, it would be amazing if this permission system could be somehow released as an open-sourced library to ease utilization in other projects / architectures.

**Comment by Natim** [comment]
Yes that is a good idea.

**Comment by ametaireau** [comment]
@Lothiraldan you're more than welcome to do so if you want to. Otherwise we'll do it but don't know when yet.

**Comment by Natim** [comment]
I guess this is what you should use instead: https://ory.gitbooks.io/hydra/content/access-control.html#warden
