### ISSUE TITLE
Error in authorization if no root factory is defined

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#348]
```
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 241, in _permitted
    permission)
  File "/home/mathieu/Code/Mozilla/cliquet/cliquet/authorization.py", line 27, in permits
    if context.prefixed_userid:
AttributeError: DefaultRootFactory instance has no attribute 'prefixed_userid'
```

If the permission system is not used (e.g. readinglist), then it's a pity to query the permission backend. 

Suggestions:
* Add default value for root factory kwarg to ``cliquet.authorization.RouteFactory`` to ``@register`` decorator
* Document clearly that ``cliquet.articles_read_principals = system.Authenticated`` can be used to bypass the permissions backend
* Or otherwise, add a simple fallback like this one in authorization policy:

```python
    def permits(self, context, principals, permission):
        # If no root factory, just required authentication.
        if not isinstance(context, RouteFactory):
            return Authenticated in principals
```

**Comment by Natim** [comment]
:+1:

**Comment by Natim** [comment]
I think it makes sense to use the RouteFactory everywhere.
Also it makes sense to let people use cliquet without the permission layer.

Which means : ``parent_id = prefixed_userid`` and ``Authentication`` required

**Comment by ametaireau** [comment]
+1 for `cliquet.authorization.RouteFactory` in the register. Please don't do it only at the decorator level.

**Comment by leplatrem** [comment]
Ok, so if I understand your feedbacks correctly:

* `cliquet.authorization.RouteFactory` in the register → **todo**
* ``parent_id = prefixed_userid`` → done already
* ``system.Authenticated`` required only → **todo doc** + default setting in readinlist init

**Comment by Natim** [comment]
Actually the solution might be to do that in the readinglist:

    https://github.com/mozilla-services/kinto/blob/master/kinto/__init__.py#L29

**Comment by ametaireau** [comment]
I prefer to have decorators that works out of the box (without requiring specific extra steps).

Also, it seems better to not impose a default context factory to *all* routes, but only to cliquet ones. Otherwise, implementers *need* to define the `factory` to `None` which might not work well with already existing pyramid toolkits which don't expose a way to specify the `factory`.

**Comment by ametaireau** [comment]
Related: https://github.com/mozilla-services/cliquet/issues/322
