### ISSUE TITLE
Export spec from test output (nose - rst - reporter) and add in documentation

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#359]
Since the test functions are written in a readable way, that could make sense to actually have these in the documentation directly, for people to read.

At first, we wanted to have this (because it was possible). I now wonder if that makes a lot of sense, and what we are trying to accomplish with it.

**Comment by leplatrem** [comment]
The intention was to:
* expose the specifications of *Cliquet* somewhere
* present a complete specification of the server and the protocol (useful for reimplementation in another techno, bugs tracking, etc.)
* force us to write tests as specifications

**Comment by leplatrem** [comment]
It could have been a good idea, but nobody would read a page with 500 lines of specs :)
