### ISSUE TITLE
Write a MaidSafe backend for Cliquet

### ISSUE THREAD

**Issue by bolet** [mozilla-services/cliquet#362]
MaidSafe is a p2p storage system, with no single point of failure (serverless).
Latency for sync not being a priority, it would make sense to experiment Cliquet with it.
http://maidsafe.net

**Comment by Natim** [comment]
You could also consider deploying Kinto/Cliquet on [Ceph](http://ceph.com/)

**Comment by tarekziade** [comment]
Closing this, @bolet if you are making any progress on this idea, please consider opening a bug in https://github.com/Kinto/kinto/issues - cliquet is being integrated there
