### ISSUE TITLE
Pagination loop when the number of records is a multiple of the limit

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#366]
It is the case with the loadtest.

The before last page is:

    http://localhost:8888/v1/buckets/d31028b0-f297-125a-681a-91f99e3cb3b0/collections/articles/records?_limit=20&\ 
    _token=eyJsYXN0X21vZGlmaWVkIjoxNDM2MzYyNjI4ODQ5fQ%3D%3D

The last page is:

    http://localhost:8888/v1/buckets/d31028b0-f297-125a-681a-91f99e3cb3b0/collections/articles/records?_limit=20&\
    _token=eyJsYXN0X21vZGlmaWVkIjoxNDM2MzYyNjMwOTQxfQ%3D%3D

And the last page give the token of the before last one so we have a loop.

**Comment by Natim** [comment]
- [ ] Update the kinto loadtests. https://github.com/mozilla-services/kinto/blob/118-test-tutorial/loadtests/loadtest/simulation.py#L236

**Comment by leplatrem** [comment]
We could possibly add something like a sentinel in the token that tracks the *current* offset in terms of records, especially in order to attest that we're serving the last page (using total-records)
