### ISSUE TITLE
Partial responses

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#384]
It would make sense to think about partial responses (some discussion [started here](https://github.com/mozilla-services/readinglist/issues/35) a while ago).

A simple approach would be to add something like ``?_fields=title,category.name``.

Source: http://blog.octo.com/en/design-a-rest-api/#partial

**Comment by leplatrem** [comment]
Source: 
* http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
* [Limiting which fields are returned by the API](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#limiting-fields)

**Comment by MrChoclate** [comment]
Is this UserResource asking for partial response to storage?
Or is this UserResource that filter the reponse of the storage?

**Comment by leplatrem** [comment]
I would vote from filtering the result from storage. Otherwise we have to implement the filtering in every storage backend.

**Comment by MrChoclate** [comment]
I agree, it will only be interesting if a backend storage could do the filtering efficiently. I'll do the PR this week ;)
