### ISSUE TITLE
Document what to do on API changes

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#396]
Following #391 discussion, we should write down the process for an API change. (e.g. doc impact, deprecation process, etc.)

**Comment by leplatrem** [comment]
Side note: we've just merged #324 which uses a constant for the current protocol version

**Comment by tarekziade** [comment]
I think we have a good pattern now : the doc has an API page per major version.

@Natim if you feel we miss something, please start a fresh discussion on the other tracker.
