### ISSUE TITLE
CORS is missing on unknown URL (404)

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#414]
CORS are present when a 404 occurs from a resource missing record.

However when the URL is unknown, the ``reapply_cors`` method has no effect (since ``utils.current_service()`` returns ``None``)

Note: This was reported here https://github.com/mozilla-services/syncto/issues/5

**Comment by ametaireau** [comment]
I believe that in Kinto we could bypass the default Cornice behaviour and apply the CORS settings listed in the default `Service` class. (without looking at what current_service) is.
