### ISSUE TITLE
Python API is not displayed on documentation

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#433]
Nor here: http://cliquet.readthedocs.org/en/latest/reference/errors.html
Nor in the Kinto documentation.

**Comment by leplatrem** [comment]
It is actually a lot worse than that ! None of the Python API is displayed !

Locally : 

![capture d ecran de 2015-09-09 10 25 48](https://cloud.githubusercontent.com/assets/546692/9756829/2e854c6c-56dd-11e5-8d20-d93be7ee9f13.png)


On RTD : 

![capture d ecran de 2015-09-09 10 26 29](https://cloud.githubusercontent.com/assets/546692/9756850/475a14e8-56dd-11e5-92d4-42973ad8650d.png)

**Comment by Natim** [comment]
Oh if the difference is between local and distant, it is probably a requirement.txt missing in the RTD configuration.

**Comment by ametaireau** [comment]
It might be that kinto isn't installed locally in there, yes!

**Comment by leplatrem** [comment]
I just checked the readthedocs admin, and indeed `cliquet` is not available.

Lots of errors like:
```
/home/docs/checkouts/readthedocs.org/user_builds/cliquet/checkouts/latest/cliquet_docs/quickstart.rst:209: WARNING: autodoc: failed to import function u'initialize' from module u'cliquet'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cliquet/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named cliquet
/home/docs/checkouts/readthedocs.org/user_builds/cliquet/checkouts/latest/cliquet_docs/reference/cache.rst:10: WARNING: autodoc: failed to import class u'PostgreSQL' from module u'cliquet.cache.postgresql'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cliquet/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named cliquet.cache.postgresql
```

/me investigating...

**Comment by leplatrem** [comment]
I fixed it with this option : 

![capture d ecran de 2015-09-10 11 17 31](https://cloud.githubusercontent.com/assets/546692/9784754/988e75fe-57ad-11e5-8141-4c012ae4be0b.png)

**Comment by Natim** [comment]
Cool thanks :)

**Comment by ametaireau** [comment]
Great.
