### ISSUE TITLE
Settings names based on project name

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#448]
One of the drawbacks of using cliquet in your app is that your settings names are prefixed with ``cliquet.`` (see [previous discussion](https://github.com/mozilla-services/cliquet/issues/318)).

Same for the management command, called ``cliquet`` to migrate ([see related kinto issue](https://github.com/Kinto/kinto/issues/129))

What if, in Cliquet, we would read the settings with a *dynamic* namespace based on the project name (this only one would be ``cliquet.project_name`` though) ?
Instead of having to define ``cliquet.http_host`` in the application, we would define ``readinglist.http_post``...

Didn't look about possible implementation so far. Just thinking loudly.

**Comment by ametaireau** [comment]
I actually quite like this idea! The implementation doesn't seem too complex either so I would say, just let it be!

**Comment by n1k0** [comment]
I like it too! +1

**Comment by leplatrem** [comment]
Yes, indeed, we could add something like that : 

```python 
    def setting(request, setting, *args):
        settings = request.registry.settings

        project = settings['cliquet.project_name']
        key = '%s.%s' % (project, setting)
        if key not in settings:
            # Retro-compat
            key = 'cliquet.%s' % setting

        if args:
            default = args[0]
            return settings.get(key, default)
        return settings[key]

    config.add_request_method(setting, 'setting')
```

And use it in views:

```python

    limit = request.setting('batch_max_requests')

```

I recalled this when @phrawzty mentionned an events helper in Daybed :)
