### ISSUE TITLE
Deactivate Cache Headers when Authenticated.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#449]
When updating a collection, we should disable cache headers.

**Comment by leplatrem** [comment]
Regarding single record updates (PATCH/PUT), the response body will return the last version of the records.

So naively I would say that it concerns the `GET record` more than the collection.

Could you explain why you thought of collection specifically?

**Comment by Natim** [comment]
I suspect that when using KWAC to update the collection it can be difficult to sync your local records against a cached collection because each time you will call the sync you may get cached values.
Also if the ``_since`` changed inbetween, it will probably re-cache correctly but not necessarily with the right values for the public.

We may delay this until we see a problem to update cached collection but we should start thinking about problems when updating cached-collections.
