### ISSUE TITLE
Refactor disabling of endpoint

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#46]
I believe we should get rid of the code that disables the DELETE endpoint on collections via a specific setting.

IHMO, this should be : 
* out of cliquet scope (eg. do in readinglist endpoint override)
* applied to any endpoints through generic configuration (setting like ``{method}_{collection|record}_{resource}_enabled``)
* through options during registering of resource (see #12)

**Comment by leplatrem** [comment]
Rel #12

**Comment by leplatrem** [comment]
I would have closed this, since we still have this in the code:
https://github.com/mozilla-services/cliquet/blob/master/cliquet/resource.py#L401-L404

**Comment by Natim** [comment]
Oh really. Ok.
