### ISSUE TITLE
Cache authentication during batch request

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#462]
Currently, BATCH requests are validated for each sub-request, creating an overhead. We could cache the verification step in order to gain RPS.

**Comment by Natim** [comment]
We could use what @leplatrem did for Kinto/kinto#197

**Comment by ametaireau** [comment]
Actually we need to be extra careful with this: we can cache the authentication but not the authorization, otherwise it would open a backdoor with the BATCH.
