### ISSUE TITLE
Handle Hawk signature with BATCH subrequests

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#463]
Currently, BATCH operations need each request to specify their authentication. This is okay for BasicAuth but can be trickier for other authentication schemes. For instance, hawk needs each request to be signed with the content of the request, which adds complexity on the client side for almost no benefit.

One way to solve this and make it easier for clients would be to allow the specification of credentials in the BATCH request headers, and do not need to specify it during the sub-requests.

**Comment by leplatrem** [comment]
As far as I know this is already the case. The headers of the original request during a batch are passed to the subrequests.

**Comment by Natim** [comment]
> The headers of the original request during a batch are passed to the subrequests.

This is the problem with Hawk because each request must be signed with a proper signature. (The batch signature will fail on the subrequest)

**Comment by tarekziade** [comment]
we don't use hawk anymore

**Comment by Natim** [comment]
> we don't use hawk anymore

What do you mean?
