### ISSUE TITLE
Investigate bdist_wheel extra_requires

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#479]
For platform or python version specific dependencies, we could investigate with extra_requires (see https://github.com/jkbrzt/httpie/blob/master/setup.py#L58-L65)

http://wheel.readthedocs.org/en/latest/#defining-conditional-dependencies

**Comment by tarekziade** [comment]
@natime do you have a use case in mind ? e.g. a lib we use where we need this ?

If so, please re-open in the Kinto tracker with the lib

**Comment by Natim** [comment]
Yes we have different dependencies in cliquet and now kinto.core for PYPY and CPython for instance.

The solution we chose is to create two wheel.
