### ISSUE TITLE
Document the format of supported patch

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla-services/cliquet#482]
Hello,

the documentation doesn't explicitly tell which patch format it supports. Does it support only key-value replace?

Is json-patch format (http://jsonpatch.com/) (http://tools.ietf.org/html/rfc6902) support planned in the future?

**Comment by leplatrem** [comment]
Thanks @Lothiraldan for the pointer about JSON-Patch (hadn't heard of it).

So far, it only supports key-value replace.

But it add support of JSON Patch via `Content-Type: application/json-patch+json`  would be great.
