### ISSUE TITLE
Deactivate notification by default and only activate selected one in the configuration

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#492]

**Comment by leplatrem** [comment]
Could you please develop your point ?

I trust Pyramid to be fast enough when notifying event that have no listeners.

I thought you were going to write about plugging listeners per resource / per action...

**Comment by leplatrem** [comment]
Meanwhile I slept, and it became clearer :)

Why not just add some parameters at the listener level ? The listener will then be in charge to read the filters in config and ignore some of the incoming events...

```
cliquet.listeners.redis.actions = update delete
cliquet.listeners.redis.resources = mushroom users
```

**Comment by Natim** [comment]
Yes this is exactly what I meant.
