### ISSUE TITLE
Handle ACTION.READ notification activation.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#493]

**Comment by leplatrem** [comment]
I don't see any use case for this TBH.

But this could be discussed : should the listener be in charge of filtering READ actions or should we prevent read events to be triggered. This is actually linked to #492

**Comment by Natim** [comment]
Actually there are 4 ACTION that we may want to listen to:

 - CREATE
 - READ
 - UPDATE
 - DELETE

Because we will be activating listener on an ACTION and RESOURCE basis with the configuration IMHO it is not a good strategy to say that we will wait for a use case for that because it is just an event like UPDATE/CREATE and DELETE

One use case we have is to count the number of view for a resource, etc.

**Comment by leplatrem** [comment]
> One use case we have is to count the number of view for a resource, etc.

We don't have statsd for that ? `#tryin'`

**Comment by Natim** [comment]
Let say you want to plug InfluxDB or Elasticsearch instead?
