### ISSUE TITLE
Monitor events listeners with statsd

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#503]
As proposed in #488 - add statsd calls in cliquet.

**Comment by Natim** [comment]
We already have statsd support.

 - http://cliquet.readthedocs.org/en/latest/reference/configuration.html?highlight=statsd#monitoring-with-statsd
 - https://github.com/mozilla-services/cliquet/blob/master/cliquet/statsd.py
 - https://github.com/mozilla-services/cliquet/blob/master/cliquet/initialization.py#L246-L286

You can use it like we do in syncto: 
 - https://github.com/mozilla-services/syncto/blob/a8304a76751292fbc5620fb3578fb4f5109cc8c6/syncto/views/record.py#L64-L66
