### ISSUE TITLE
No link to go to the notification page in the documentation.

### ISSUE THREAD

**Issue by MrChoclate** [mozilla-services/cliquet#535]
I did not find a way to access notification page in the documentation:
http://cliquet.readthedocs.org/en/latest/reference/notifications.html

Maybe add it to the Internals section?
And add a link to it here:
http://cliquet.readthedocs.org/en/latest/reference/configuration.html#notifications
because when we see it we want to know the payload.

**Comment by Natim** [comment]
This should be fixed once https://github.com/mozilla-services/cliquet/pull/534 is merged.
