### ISSUE TITLE
Server should add a header to tell clients when it was flushed.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#536]
It is the only way to tell client for sure that they need to reupload everything they have locally.

The idea is to add ``Last-Flushed`` header that could be read from the config or the ENV variable and then from the cache backend (if we want to support the ``/__flush__``) endpoint.

**Comment by leplatrem** [comment]
Another approach would be to do it in Kinto, and add specific header when the collection is created implicitly in the default bucket...

**Comment by leplatrem** [comment]
I think this should be implemented in Kinto this way:
* The `/__flush__` endpoint stores the current timestamp (current time) in the cache backend
* We add a header `Server-Flush` that gives the value to the client
* With memory backend, we set `Server-Flush` on server start 
* The client obtains this server-flush, if it is superior to `_since` then it means the server was flushed meanwhile

Thoughts?

**Comment by Natim** [comment]
Yes it seems good to me :+1:
