### ISSUE TITLE
Make error message explicit

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#545]
https://github.com/mozilla-services/cliquet/blob/master/cliquet/storage/postgresql/client.py#L61

"PostgreSQL dependencies missing" is not very clear. 

Should be "SQLAlchemy missing" maybe ?

**Comment by Natim** [comment]
Actually the way to install cliquet postgresql dependency is to use:

    pip install cliquet[postgresql]

rather than just installing SQLAlchemy.

**Comment by tarekziade** [comment]
@natim this is unrelated to the issue

**Comment by leplatrem** [comment]
Would you prefer a link to docs in the error message? Or suggesting the command to run?

Or *Python libraries for PostgreSQL are missing* ?

**Comment by tarekziade** [comment]
I would explicitly indicate in the error which dependency is missing or has a problem.

```python
message = ("PostgreSQL sqlalchemy dependency missing. "
                   "Refer to installation section in documentation.")
```

The reason is that sometimes you can have an installation error and knowing which lib is screwed can be useful.

**Comment by leplatrem** [comment]
We wanted to avoid mentioning it explicitly, but if it can make sense, why not!

As @Natim said there are several ones, but I think that if some of the other ones are missing, it fails somewhereelse within sqlalchemy. So why not mentionning sqla here indeed...

**Comment by tarekziade** [comment]
> As @Natim said there are several ones

yes, in this code, I see "if sqlachemy is None:"
