### ISSUE TITLE
Use cache backend to store results of storage and permissions 

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#558]
* Prevent query of storage/permission when nothing has changed
* Invalidate cache when resource is changed
* Better if optional (using decorators and notifications?)

Questions:
* How to invalidate memory backend across several workers? :)

**Comment by tarekziade** [comment]
> How to invalidate memory backend across several workers? :)

If by worker you mean process, I think it's a fair limitation to have: the memory backend should be used with caution in a multi-processing environment.  

Note that we can have multi-process memory caches easily at the uwsgi or nginx level, or even do fun and complex stuff at the system level, like sending a signal to other processes that they should purge their memory cache.
