### ISSUE TITLE
Add timeout option for Redis client

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#582]
https://redis-py.readthedocs.org/en/latest/#redis.Redis

What about postgres ?

**Comment by Natim** [comment]
Do you mean we should define one? What is the strategy in case there is a timeout during a command?

**Comment by leplatrem** [comment]
When the redis is instantiated ([here](https://github.com/mozilla-services/cliquet/commit/df98652f6e4afb98d075e36c4fd2553a5727dea8#L25-L40)), we could add a timeout value.

The connection pool object can received a `socket_timeout` option. 

The setting should be named `timeout_seconds`, converted to `float` and should be `None` by default.

The documentation of configuration should be updated too.

**Comment by vsham20** [comment]
I would like to work on this bug.

**Comment by Natim** [comment]
@vsham20 I have assigned you to it.

**Comment by vsham20** [comment]
Great, I'll work on this.

**Comment by tarekziade** [comment]
@vsham20 I moved it to the Kinto tracker since we've merged both code bases
