### ISSUE TITLE
Create an API to rename collections

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#583]
I had this use case: rename a collection or a bucket that already has some data. 

The goal is to avoid re-creating all the data just to change a collection name. 

Would it be interesting to have this API ?

**Comment by tarekziade** [comment]
Natim suggested a redir feature

**Comment by Natim** [comment]
The interesting feature that comes with renaming is to keep records timestamp and collection timestamp.

Also the redirection would ease the modification for clients that keep talking with the previous endpoint.

**Comment by tarekziade** [comment]
Thinking again about the redirection, I am a bit worried that it's overkill: it will add maintenance burden in Kinto (when do we remove the alias? or are we keeping it forever?) , when this sounds like an ops issue. e.g. we can always redirect from the reverse proxy.

**Comment by Natim** [comment]
Closing as wontfix?

**Comment by leplatrem** [comment]
TBH I don't see too much value for this, especially in cliquet where resources URLs could be anything.

As for Kinto it could be a management command using the low-level storage class for example.

**Comment by tarekziade** [comment]
> Closing as wontfix?

The question about an API to rename still stands I think. 

> As for Kinto it could be a management command using the low-level storage class for example.

Sounds cool, as long as the storage class let us rename records bucket and/or collection names ?

**Comment by leplatrem** [comment]
> Sounds cool, as long as the storage class let us rename records bucket and/or collection names ?

Not, but listing and recreating from there won't trigger notifications :)

**Comment by tarekziade** [comment]
mmm so for example if I have 3000 records, I need to delete the and recreate them ? 

Can't we do a single UPDATE query in postgres ?

**Comment by leplatrem** [comment]
> Can't we do a single UPDATE query in postgres ?

Well you could, using a new `move()` method, but then you need to implement it for redis too :)

3000 is a piece of cake. 30000 could take a few seconds. you would start to have time for a coffee around 300000 :)

**Comment by leplatrem** [comment]
One thing: recreating would bump existing stamps.

**Comment by tarekziade** [comment]
> Well you could, using a new move() method, but then you need to implement it for redis too :)

Is this an issue ?

> 3000 is a piece of cake. 30000 could take a few seconds. you would start to have time for a coffee around 300000 :)

My concern is not about the number of records, but rather about the fact that while I interact with the database with 3000 requests or so, it can create havoc if other nodes are interacting with the database with the same collection. A single atomic request seemed to me like a good solution to reduce this friction.  For example what happens if another node tries to add a collection while you are removing all records from it ?

**Comment by leplatrem** [comment]
Adding a `move(parent_id, new_parent_id, collection_id, new_collection_id)` is probably the best option. And as you pointed out, it would be the only way to explicit run the sql command to explicitly lock the `records` and `deleted` tables. 

Regarding timestamps, unfortunately the current triggers are too vague, and would bump the timestamp even if we just update the `collection_id` column:
```
CREATE TRIGGER tgr_records_last_modified
BEFORE INSERT OR UPDATE ON records
FOR EACH ROW EXECUTE PROCEDURE bump_timestamp();

CREATE TRIGGER tgr_deleted_last_modified
BEFORE INSERT OR UPDATE ON deleted
FOR EACH ROW EXECUTE PROCEDURE bump_timestamp();
```

They should be replaced by this, which only targets the `data` column instead:

```
CREATE TRIGGER tgr_records_last_modified
BEFORE INSERT OR UPDATE OF data ON records
FOR EACH ROW EXECUTE PROCEDURE bump_timestamp();

CREATE TRIGGER tgr_deleted_last_modified
BEFORE INSERT ON deleted
FOR EACH ROW EXECUTE PROCEDURE bump_timestamp();
```

**Comment by tarekziade** [comment]
I agree the timestamp should be bumped. It's a hell of a modification ;)

**Comment by tarekziade** [comment]
In terms of implementation, do we want to provide an HTTP API or just make this an admin tool ?
I guess an HTTP API is useful, as long as its permission is tied to the owner ?

**Comment by Natim** [comment]
> I agree the timestamp should be bumped. It's a hell of a modification ;)

Then you do not need this move method, the goal of this move method is not to change the timestamp in order to make sure the collection of records are not downloaded again by clients.

**Comment by Natim** [comment]
> In terms of implementation, do we want to provide an HTTP API or just make this an admin tool ?

It depends if we consider this as a common practice or as a exceptional one.

I would rather go for the later and create an admin tool for "power users" that knows what they are doing.

I do not think a usual client (such as Kinto.js) should have to do that ever.

**Comment by tarekziade** [comment]
> Then you do not need this move method, the goal of this move method is not to change the timestamp in order to make sure the collection of records are not downloaded again by clients.

What ? Changing the timestamps or not when we're renaming a collection is a decision we need to make.
But that does not mean we don't need a move feature. For me,  the goal of this move method is to move a list of records in the most efficient way. 

If we don't have a move method, how do we do it without facing the issues described in my previous comments ?

> I do not think a usual client (such as Kinto.js) should have to do that ever.

So, you are saying no collection renaming in Kwak   ?

**Comment by tarekziade** [comment]
that'll come back later through the CLI and kinto-admin
