### ISSUE TITLE
Ability to specify last_modified value when updating records

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#587]
One current limitation of the current protocol is that fact that the `last_modified` metadata (on buckets, collections and records) cannot be set from an external source.

For instance, if one wants replicate the data between two instances (origin and destination), when pushing the updates, the `last_modified` field from the origin data will be replaced by a new one defined by the destination.

As such, the data between the two instances cannot be considered equal.

One way to fix this would be to let the client define what the `last_modified` field is, checking for some heuristics: the new `last-modified` cannot be less than the `max(collection)` for instance.

**Comment by almet** [comment]
Another heuristic, that will be helpful when the client sends back the data it got from the last time:

- if the data is passed with a `last_modified` field that equals the one specified in the `If-Match` header, then drop the one from the data and replace it with a new one from the server.

**Comment by leplatrem** [comment]
I would rename this issue : *Ability to specify last_modified value when posting records*

>  cannot be less than the max(collection) for instance.

How would that work on empty collections?

> equals the one specified in the If-Match  then drop the one from the data and replace it with a new one from the server

Why not indeed. And for create with `If-None-Match: *` just check unicity? not less than max() ?

Side note: The trigger has to be modified https://github.com/mozilla-services/cliquet/issues/583#issuecomment-158010100

Do we have a use-case for this? Like importing initial data? (ref https://github.com/Kinto/kinto.js/pull/265)

**Comment by Natim** [comment]
> the new last-modified cannot be less than the max(collection).

I don't think we should add this limitation, but more the limitation were the last-modified value cannot be less than the previous one.

Then we should also make sure the two server collection timestamp are in sync at the end of the synchronization.

> Do we have a use-case for this?

The use case is to be able to do kinto2kinto collection synchronization for the collection signature feature.

**Comment by almet** [comment]
I've renamed to "Ability to specify last_modified value when *updating* records" since it's not only for POSTing.

- For empty collections, you just don't max out the value;
- For create with `If-None-Match: *`: I think we need to check the unicity (I thought this is the intended use case of this header).

The use case for this is replication of kinto collections, for the signatures.

**Comment by almet** [comment]
> I don't think we should add this limitation, but more the limitation were the last-modified value cannot be less than the previous one.

I believe It has the same effect.

**Comment by almet** [comment]
Ah, gotcha: you're saying the `last-modified` shouldn't be less than the previous one *of the record*. Agreed.

**Comment by Natim** [comment]
Today, if you want to sync Alice and Bob servers, you cannot do it because they will never end-up to be in sync both ways.

This is due to the fact that the last-modified value will always be bumped when you put it on the server even if it is the same exact record so they will always be marked as changed.
