### ISSUE TITLE
Don't hmac userids with a server secret

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#589]
Currently, [userids are hmaced with a secret only known by the server](https://github.com/mozilla-services/cliquet/blob/26f48ef35237e07efe1ea51b8d81b17c03e2b0a8/cliquet/authentication.py#L31).

This prevents the ability to replicate the permissions from one server to another, since the user_id would differ in these different instances.

Are we forced to hash the `user_id`, and if yes, why?

**Comment by leplatrem** [comment]
> Are we forced to hash the user_id, and if yes, why?

It's only the case with Basic Auth by the way.


See with FxA, user id comes from oauth info: https://github.com/mozilla-services/cliquet-fxa/blob/master/cliquet_fxa/authentication.py#L83

**Comment by almet** [comment]
Ah, perfect then. We should deprecate the use of Basic Auth in our examples etc, otherwise people will rely on it due to its simplicity of use.
