### ISSUE TITLE
Deprecate the use of Basic Authentication in the examples

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#590]
Currently, the demo instances and the code in the tutorial are relying on Basic Authentication. We should get rid of these examples and let the users directly rely on OAuth providers instead, since Kinto is built around this concept (and Basic Auth prevents replication between servers, for instance).

**Comment by leplatrem** [comment]
I would not deprecate it until a very simple *built-in* alternative exists.

> [...] since Kinto is built around this concept 

What do you mean ? I don't see why Kinto is mentionned here :)

**Comment by almet** [comment]
Well, Kinto or Cliquet. The user id should be unique, and the way to do this is to rely to an external authn provider, and all of the services we integrate with are integrable by using OAuth.

I don't know what you mean by "built-in", but I believe we should make it really easy to have the examples integrate with Github / Twitter / Facebook authentication, for instance, and I don't want to have these in the core of Cliquet.

However, having them defined as extra-dependencies can make sense, such as you don't need to do much more than `pip install kinto[github]`.

**Comment by almet** [comment]
Actually, this issue should go in the Kinto bugtracker and not here.
