### ISSUE TITLE
Changes to the hello view

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#598]
see https://github.com/Kinto/kinto/pull/300

Proposed changes : 

- [x] add **http_api_version** only when set by a concrete implementation 
- [x] rename **version** to **project_version**
- [x] rename **protocol_version** to **cliquet_protocol_version**
- [x] rename **hello** to **project_name**

**Comment by leplatrem** [comment]
> pkg_versions

Do we need that ? How do know which packages to include there? In case of a known security issue for a package at a particular version, don't we want to hide it as much as possible ?

> rename protocol_version to cliquet_protocol_version

Why not (instead) setting `http_api_version` to the `cliquet protocol version` value if not set ?

**Comment by tarekziade** [comment]
> Do we need pkg_versions ?

I don't know, I see "version" right now, and I am trying to find it a better place. If we don't need it let's remove "version" ?

> Why not (instead) setting http_api_version to the cliquet protocol version value if not set ?

Because as far as I understood, the cliquet protocol is not enough to describe a concrete and working HTTP API. e.g. "it's another beast" :)

**Comment by tarekziade** [comment]
This issue is being worked in the https://github.com/mozilla-services/cliquet/tree/http_api_version branch

**Comment by Natim** [comment]
I think we can just rename ``version`` to ``project_version`` and ``documentation`` to ``project_documentation`` if you like this prefix.

**Comment by Natim** [comment]
@tarek shall we use the same MAJOR.MINOR formalism to describe the cliquet_protocol_version?

**Comment by tarekziade** [comment]
> I think we can just rename version to project_version and documentation to project_documentation if you like this prefix.

ok sure,

**Comment by tarekziade** [comment]
> In case of a known security issue for a package at a particular version, don't we want to hide it as much as possible

so what do we do for this ? do we keep project_version (old: version) or not ?

**Comment by Natim** [comment]
We could add a settings ``cliquet.hide_version_numbers`` as we have for nginx ``server_tokens off;``

**Comment by tarekziade** [comment]
Before we add more complexity, can someone explains what this information is used for and by whom ?

**Comment by Natim** [comment]
It is used by ops and by us to see which version is deployed (if stage and production are using the same for instance)

**Comment by tarekziade** [comment]
> It is used by ops and by us to see which version is deployed (if stage and production are using the same for instance)

This is why I suggested a pkg_versions that contains all the packages version. And as @leplatrem said, maybe we should be careful about the implementation details information we make visible.

Maybe like __heartbeat__ we should have a dedicated view that exposes implementation details like that

**Comment by Natim** [comment]
I think we can start by adding pkg_version on the hello page for now and iterate.

**Comment by tarekziade** [comment]
let's drop pkg_version for now

**Comment by tarekziade** [comment]
closing this one, go at https://github.com/mozilla-services/cliquet/pull/600
