### ISSUE TITLE
Remove the versioning doc

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#599]
Remove
 https://github.com/mozilla-services/cliquet/blob/master/cliquet_docs/api/versioning.rst

See https://github.com/Kinto/kinto/pull/300

**Comment by Natim** [comment]
The idea was to have the same versionning for all projects depending on Cliquet.
This file is used for kinto and syncto versionning documentation

**Comment by leplatrem** [comment]
It's ok to leave it in *Cliquet*, even though we subsituted it by a custom one in Kinto. I'm closing this, please re-open if you don't agree!
