### ISSUE TITLE
Permissions and partial response

### ISSUE THREAD

**Issue by MrChoclate** [mozilla-services/cliquet#605]
I continue the discussion of #601 here.

What should the behavior of a ShareableResource be when using the `?_fields` parameter.
Currently permissions are not displayed. It should work if you use `?_fields=__permissions__` as a hack.

@Natim said we should be able to add permissions of each record using `?_fields=permissions`. This is no longer fields filtering.

We could override `_extract_fields()` to add the permissions to each record if `?_fields=__permissions__` (or `fields={{permission_field}}`). I think it is better than `?_fields=permissions`.

**Comment by Natim** [comment]
If we can get the permission without having to call the permission backend (ie with ``__permission__``) then we should probably add it to the list by default and lets add it to the ``_fields=permissions``

We should not expose ``__permissions__`` nor let expose __*__ fields on the public API.

**Comment by MrChoclate** [comment]
In a record:
Since `permissions` is outside of `data` (why?), `_fields=permissions` is a special case but it can easily be handled. 

In a collection:
There is currently no `__permission__` in each record, right? Why?
If it is added, and transform into `permissions` partial response will work.
If there is no `__permission__` on purpose, extra work must be done and `_fields=permissions` become also a special case.

**Comment by MrChoclate** [comment]
I'd like to contribute because of #547. But first I need to know your design choice about permissions ;)

**Comment by tarekziade** [comment]
@MrChoclate is this still an active issue ?  I am wondering if we currently have a real-world use case for this feature.

If it's the case please let me know we will start a new issue in Kinto

Thank you!
