### ISSUE TITLE
Add hooks to allow plugins to run some code on migrate

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#606]
If a plugin requires to perform some actions when the `migrate` command is ran, having a hook could be useful.

Django has something like that : https://docs.djangoproject.com/en/1.8/ref/signals/#pre-migrate

**Comment by tarekziade** [comment]
Do you have a use case where we need that ?

**Comment by leplatrem** [comment]
I was thinking of initializing elasticsearch indices or stuff like that.

We can leave close and revamp when concretely needed
