### ISSUE TITLE
moving to enum.Enum

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#646]
We have an ad-hoc Enum class at https://github.com/mozilla-services/cliquet/blob/master/cliquet/utils.py#L152

it behaves very differently from Python 3.4 Enum - https://docs.python.org/3/library/enum.html and even makes our Project shadow the stdlib Enum in 3.4

I don't see any good reason to keep ours, as we can use "enum34" which backports enum in all Python version.

However, that's not a small change - so I'd like to ask here before doing it - in case I am missing a good reason to keep it

**Comment by tarekziade** [comment]
see the async notif for how that change can look like https://github.com/mozilla-services/cliquet/pull/647

**Comment by Natim** [comment]
For a long time Enum wasn't standardised in Python. I am glad we can now use an official version.

That seems like a good idea to me.

**Comment by leplatrem** [comment]
Merged in #652
