### ISSUE TITLE
Documentation : Getting started section needs update

### ISSUE THREAD

**Issue by ayusharma** [mozilla-services/cliquet#655]
If we use a scaffold `pcreate -s starter MyProject`  to create a project in pyramid. it makes `development.ini` and `production.ini` files instead of `myproject.ini` .

**Comment by ayusharma** [comment]
@Natim  Should I change myproject.ini file to development.ini in docs ?

**Comment by leplatrem** [comment]
> Should I change myproject.ini file to development.ini in docs ?

Yes, good idea!
