### ISSUE TITLE
Add tests and document how to add an administrator in the config.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#659]
I have tried to add a ``bucket_read_principals`` in the configuration but it seems that all permissions on the bucket are then broken.

**Comment by leplatrem** [comment]
Isn't related to Kinto ? See https://github.com/Kinto/kinto/issues/350

**Comment by tarekziade** [comment]
I think so. Let's fix https://github.com/Kinto/kinto/issues/350
