### ISSUE TITLE
ConnectionError: Error 8 connecting to localhost:6379. nodename nor servname provided, or not known.

### ISSUE THREAD

**Issue by ayusharma** [mozilla-services/cliquet#664]
I am getting this error while `make tests`:

```
ConnectionError: Error 8 connecting to localhost:6379. nodename nor servname provided, or not known.
IOError: [Errno 24] Too many open files
```
I only got these errors on Mac Os X and in ubuntu everything works fine. 

After sometime I resolved the error using :

```
$ ulimit -n 1024
```

ulimit :  It increases the open file limit for a non-root user.

Should we add this to troubleshooting documentation ?

**Comment by Natim** [comment]
Yes definitely :+1:

**Comment by leplatrem** [comment]
Fixed #666

**Comment by guzhenping** [comment]
l try ,but it did not work

**Comment by Natim** [comment]
You need to do it in the shell running the redis-server.
Which distribution are you using?

**Comment by guzhenping** [comment]
l do it in my Mac pro terminal.sorry ,l don't know my reds's distribution...l installed it via pip .

**Comment by Natim** [comment]
How do you run redis?

**Comment by guzhenping** [comment]
ok...Thank you! It's a stupid action...l have forgotten installing redis_server.
It's strange that Redis-py Website only have one command "pip install redis"..
