### ISSUE TITLE
Replace `load_from_config` by `load_from_settings`.

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#676]
Currently the backends are loaded via a `load_from_config` function, that is made availabel in each module. I wonder why this isn't `load_from_settings` since the first thing each of these function do is `    settings = config.get_settings()`.

I'm not sure if that's done on purpose or not. Do we have a rationale for this? If not, we probably should directly pass the settings and rename the function accordingly.

**Comment by leplatrem** [comment]
Some backends maybe interdependant (and thus referred using `config.registry.other`)

**Comment by almet** [comment]
Okay, closing.
