### ISSUE TITLE
Refactor to add a Service subclass with common configuration

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#68]
* error_handler
* cors_origins
* default_cors_headers

**Comment by leplatrem** [comment]
Rel #12

**Comment by leplatrem** [comment]
I would have closed this, since we still have global patching in the code: 
https://github.com/mozilla-services/cliquet/blob/master/cliquet/__init__.py#L124-L127

**Comment by Natim** [comment]
Yes but this patch is something we want to make sure that with cliquet all services are accepting CORS with the given list of origin and may return the given headers.

**Comment by leplatrem** [comment]
ah ok, I would have thought that we would do something like ``from cliquet import Service`` instead.

I'm ok with both approaches actually

**Comment by ametaireau** [comment]
That's what we're currently doing: https://github.com/mozilla-services/cliquet/blob/master/cliquet/__init__.py#L82-L87

**Comment by leplatrem** [comment]
Oh my fault I hadn't read well ...
