### ISSUE TITLE
DELETE operation always returns 200 on success, while the spec suggests otherwise

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/cliquet#682]
Refs https://github.com/Kinto/kinto-client/pull/66#issuecomment-195251192

>So, it depends which status you're getting back. The HTTP spec says that:
>
>- A 200 means that "The request has succeeded"
>- A 202 means that the request was accepted but not yet fulfilled;
>- A 204 means that "The server has fulfilled the request" but there is nothing to answer (that's what's usually used on DELETE operations)
>
>In cliquet, [it seems that we return a 200](https://github.com/mozilla-services/cliquet/blob/master/cliquet/resource/__init__.py#L499), which doesn't seem to be consistent with what you're describing here.
>
>Please, open an issue about that, yes!

**Comment by almet** [comment]
Quoting @n1k0 to add some more context to the discussion:

> it seems the server can take a lot of time to delete all buckets; more worrying, it seems it sends a success response even if the operation is not entirely done just yet.

**Comment by leplatrem** [comment]
We must return 200 with the list of objects that were deleted.
