### ISSUE TITLE
Add info about documentation generation to contributing docs

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#684]
`make docs` :)

**Comment by matheuspoleza** [comment]
@leplatrem how can I start on that?

**Comment by Natim** [comment]
Hi @matheuspoleza we are basically using Sphinx doc and the generation takes place using ``make docs`` I think you could add a paragraph directly in the contributing page maybe? What do you think?

**Comment by matheuspoleza** [comment]
@Natim good idea. The paragraph will tell just about the Sphinx and how to run `make docs`?

**Comment by Natim** [comment]
Yes

**Comment by matheuspoleza** [comment]
cool! I'll do that

**Comment by glasserc** [comment]
You might want to wait a few days first @matheuspoleza. I'm in the process of merging cliquet and kinto -- see glasserc/kinto#1 and #687, and that could have a lot of impact on your work on this bug.

**Comment by matheuspoleza** [comment]
@glasserc pl, I'll wait that merge.

**Comment by tarekziade** [comment]
@matheuspoleza the merge was done and I cloned the bug (see previous ref) thanks for your patience
