### ISSUE TITLE
Add a way to know the version of the schema in use

### ISSUE THREAD

**Issue by almet** [mozilla-services/cliquet#685]
This is useful when running migrations.

This could be `cliquet migrate --get-schema-version`

**Comment by tarekziade** [comment]
I am not sure to understand the use case 

for information purpose, do you want to add that info in / ?

**Comment by leplatrem** [comment]
Oh no I suppose that was an idea of a command line. 
Also, it only applies to `postgres` backend. Since the other backends do not have any migration (another reason not to use in production BTW)
