### ISSUE TITLE
Handle OR in get_all conditions

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#74]

**Comment by leplatrem** [comment]
Currently, we only support ``AND`` (and implicitly).

``a × b × c``

(e.g. ``min_age=28&married=false&children=2``)

When introducing OR, one of the biggest challenge is to find a sound/consistent syntax for conditions precedence.

One way to achieve would be to extend the current formalism, by bypassing the query parsing of Pyramid, and rolling out our own, for example with ``(``, ``)``, ``|``:

* ``a × b + c`` :  ``min_age=28&married=false|children=2``
* ``a × ( b + c)`` :  ``min_age=28&(married=false|children=2)``

Another way would be to have another formalism, like [Eve does](http://python-eve.org/features.html#filtering), using a ``where`` queryparam:

* ``?_where=min_age==28&(married==false|children==2)``
* ``?_where={"mongodb": "json syntax"}``

I lack of examples of existing APIs... 

Thoughts ?

**Comment by Natim** [comment]
This has been made available with the ``in_`` parameter prefix. See http://cliquet.readthedocs.org/en/latest/api/resource.html#filtering

**Comment by leplatrem** [comment]
Don't agree with closing.
