### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#78]
As required by RL https://github.com/mozilla-services/readinglist/issues/158

If I'm not mistaken, that would probably mean to:
* use structlog
* implement a heka handler (using heka-py ?)

**Comment by Natim** [comment]
No need for a heka handler, we just need to write a python lib that does the mozlog job.

**Comment by leplatrem** [comment]
structlog has a JSONRenderer, I think we might just have to introduce it in cliquet code base.

In order to benefit from value binding, we might have to store a logger reference on the request (?)

```python
# in new request
request.logger = request.logger.bind(user_id=request.user_id)
```

```python
# in resource
self.request.logger = self.request.logger.bind(resource=self.name)
...
request.logger.msg("Fetch collection", collection_count=len(results))
```
