### ISSUE TITLE
Use oauth 'state' parameter for CSRF protection

### ISSUE THREAD

**Issue by rfk** [mozilla-services/cliquet#84]
I didn't follow all the details of how the oauth `state` parameter is currently being used here, so this may be covered already.  But I wanted to make sure we sanity-check all the edge cases.

In addition to tunnelling state through the oauth dance, one of the purposes of the `state` paramter in OAuth is to provide CSRF protection by matching incoming redirects to a particular browser session.

This typically means doing something like:

  * when starting the dance, generate a nonce and set it in both a client session cookie and the outgoing `state` parameter.
  * when receiving a redirect that completes the dance, pull the nonce out of the session cookie and check that it matches the one in the returned `state` parameter.

Without this check, there are scenarios where I can trick you into completing an oauth flow with your user account but my state token, or my user account and your state token, and hence gain unauthorized access.

Some background resources on the topic:

  http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html
  http://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-00

**Comment by Natim** [comment]
You could do that but not gain unauthorized access because we are not linking the state to any session, you will then be logged to the user that finished the flow but not with the one that iniated the login flow.

**Comment by ametaireau** [comment]
I believe it's taken care of in https://github.com/mozilla-services/cliquet/blob/master/cliquet/views/oauth/relier.py#L91

However, we're not using a session cookie for this. @rfk do you see a problem with this?

**Comment by rfk** [comment]
@ametaireau indeed, I think since you're not using a session cookie this should be OK.

**Comment by ametaireau** [comment]
Thanks, closing.
